# Cloudflare Pages Configuration
name = "princeton-academic-events"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

# Pages Functions configuration
pages_build_output_dir = "frontend"

# Functions configuration - functions are at root level
functions = "functions"

# Environment variables
[vars]
# Add any environment variables here if needed
