name = "princeton-academic-events"
main = "src/index.js"
compatibility_date = "2024-01-01"

[pages]
pages_build_output_dir = "frontend/out"

[[d1_databases]]
binding = "DB"
database_name = "princeton-academic-events"
database_id = "4802e93e-ab46-4c73-b0a3-c4a80d5fc711"

[env.production]
name = "princeton-academic-events"
route = "princeton-academic-events.your-domain.com/*"

[env.staging]
name = "princeton-academic-events-staging"
