export async function onRequestGet() {
  try {
    // Read the events data generated by GitHub Actions
    const eventsData = await fetch('file://./frontend/data/events.json');

    if (!eventsData.ok) {
      return new Response(JSON.stringify({
        error: 'Events data not found',
        message: 'Data will be available after the next weekly scrape'
      }), {
        status: 404,
        headers: { 'Content-Type': 'application/json' }
      });
    }

    const data = await eventsData.json();

    return new Response(JSON.stringify(data), {
      headers: {
        'Content-Type': 'application/json',
        'Access-Control-Allow-Origin': '*',
        'Cache-Control': 'public, max-age=3600' // Cache for 1 hour
      }
    });
  } catch (error) {
    console.error('Error serving events:', error);
    return new Response(JSON.stringify({
      error: 'Internal server error',
      message: 'Unable to fetch events data'
    }), {
      status: 500,
      headers: { 'Content-Type': 'application/json' }
    });
  }
}
